server:
  port : 1025

topic_arn : << your topic arn >>
queue_url : << your queue URL >>
access_key : << your access key>>
secret_access_key : << your secret >>
aws_region : << your region >>
